name: Build-dist

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Windows dependency
      if: matrix.os == 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt -PathType leaf) {
          pip install -r requirements.txt
        }

    - name: Mac/Linux dependency
      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
            pip install -r requirements.txt
        fi
      
    
    - name: Build
      run: |
        pyinstaller -F ssa_hdrify.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ssa-hdrify-${{ matrix.os }}
        path: dist
